export const NODE_RULES_BACKEND = [
  {
    id: '99cdc3d1-4eca-4a59-a7b8-221a8daa42b5',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: null,
    parentNodeType: null,
    childNodeId: '0161260d-6862-49d1-ba53-0450fc4bef34',
    parentNode: null,
    childNodes: [
      {
        id: '0161260d-6862-49d1-ba53-0450fc4bef34',
        createdAt: '2023-03-21T17:57:58.138Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: null,
        nodeName: 'Segment',
        nodeNameType: 'segment',
      },
    ],
  },
  {
    id: '15f53561-cf3d-40d9-ada7-6dc2c21d2edc',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '0161260d-6862-49d1-ba53-0450fc4bef34',
    parentNodeType: null,
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '0161260d-6862-49d1-ba53-0450fc4bef34',
      createdAt: '2023-03-21T17:57:58.138Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: null,
      nodeName: 'Segment',
      nodeNameType: 'segment',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
      {
        id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
        createdAt: '2023-03-21T17:57:58.146Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Update Lead',
        nodeNameType: 'updateLead',
      },
    ],
  },
  {
    id: '794944d3-d9ce-44ba-b701-79d51de624bb',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNodeType: null,
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
      createdAt: '2023-03-21T17:57:58.143Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'ACTION',
      nodeName: 'Send Email',
      nodeNameType: 'sendEmail',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
      {
        id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
        createdAt: '2023-03-21T17:57:58.146Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Update Lead',
        nodeNameType: 'updateLead',
      },
      {
        id: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
        createdAt: '2023-03-21T17:57:58.148Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'DECISION',
        nodeName: 'Open Email',
        nodeNameType: 'openEmail',
      },
      {
        id: '5cbf1a25-495b-455d-8a27-353cf776d00c',
        createdAt: '2023-03-21T17:57:58.150Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'DECISION',
        nodeName: 'Download Asset',
        nodeNameType: 'downloadAsset',
      },
    ],
  },
  {
    id: '08cb8735-0a22-4cb6-85e9-e9bf5ec7c572',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
    parentNodeType: null,
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
      createdAt: '2023-03-21T17:57:58.144Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'ACTION',
      nodeName: 'Inaction Send Email',
      nodeNameType: 'inactionSendEmail',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
      {
        id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
        createdAt: '2023-03-21T17:57:58.146Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Update Lead',
        nodeNameType: 'updateLead',
      },
      {
        id: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
        createdAt: '2023-03-21T17:57:58.148Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'DECISION',
        nodeName: 'Open Email',
        nodeNameType: 'openEmail',
      },
      {
        id: '5cbf1a25-495b-455d-8a27-353cf776d00c',
        createdAt: '2023-03-21T17:57:58.150Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'DECISION',
        nodeName: 'Download Asset',
        nodeNameType: 'downloadAsset',
      },
    ],
  },
  {
    id: '4ae3d32f-36d7-4a34-a12b-bf3586a8bf4b',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '53763a17-a030-49ee-a6ff-7a4c89aab201',
    parentNodeType: null,
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
      createdAt: '2023-03-21T17:57:58.146Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'ACTION',
      nodeName: 'Update Lead',
      nodeNameType: 'updateLead',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
    ],
  },
  {
    id: '3ce7afe3-100d-4b64-a3cb-87ab6d2a0d39',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '7f9c7af3-bfff-467b-90f4-fc721044184e',
    parentNodeType: null,
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '7f9c7af3-bfff-467b-90f4-fc721044184e',
      createdAt: '2023-03-21T17:57:58.147Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'ACTION',
      nodeName: 'Inaction Update Lead',
      nodeNameType: 'inactionUpdateLead',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
    ],
  },
  {
    id: 'a775b36d-6177-4b0c-996d-27ba6e305e6c',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
    parentNodeType: 'TRUTHY',
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
      createdAt: '2023-03-21T17:57:58.148Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'DECISION',
      nodeName: 'Open Email',
      nodeNameType: 'openEmail',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
      {
        id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
        createdAt: '2023-03-21T17:57:58.146Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Update Lead',
        nodeNameType: 'updateLead',
      },
    ],
  },
  {
    id: '6b81224a-f38c-4625-98b1-2c012d81d5c3',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
    parentNodeType: 'FALSY',
    childNodeId: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
    parentNode: {
      id: 'a95ed6a6-9583-404e-869f-294e45f3b7ee',
      createdAt: '2023-03-21T17:57:58.148Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'DECISION',
      nodeName: 'Open Email',
      nodeNameType: 'openEmail',
    },
    childNodes: [
      {
        id: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
        createdAt: '2023-03-21T17:57:58.144Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Inaction Send Email',
        nodeNameType: 'inactionSendEmail',
      },
      {
        id: '7f9c7af3-bfff-467b-90f4-fc721044184e',
        createdAt: '2023-03-21T17:57:58.147Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Inaction Update Lead',
        nodeNameType: 'inactionUpdateLead',
      },
    ],
  },
  {
    id: '2a006bab-5831-48ba-85f2-87fefb45138c',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '5cbf1a25-495b-455d-8a27-353cf776d00c',
    parentNodeType: 'TRUTHY',
    childNodeId: '4bf47ebd-8604-4510-8011-c2c11964bd00',
    parentNode: {
      id: '5cbf1a25-495b-455d-8a27-353cf776d00c',
      createdAt: '2023-03-21T17:57:58.150Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'DECISION',
      nodeName: 'Download Asset',
      nodeNameType: 'downloadAsset',
    },
    childNodes: [
      {
        id: '4bf47ebd-8604-4510-8011-c2c11964bd00',
        createdAt: '2023-03-21T17:57:58.143Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Send Email',
        nodeNameType: 'sendEmail',
      },
      {
        id: '53763a17-a030-49ee-a6ff-7a4c89aab201',
        createdAt: '2023-03-21T17:57:58.146Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Update Lead',
        nodeNameType: 'updateLead',
      },
    ],
  },
  {
    id: '84997b10-cf3e-4a01-8ca4-c93e4e44be4a',
    createdAt: '2023-03-21T17:57:58.151Z',
    createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
    deletedAt: null,
    parentNodeId: '5cbf1a25-495b-455d-8a27-353cf776d00c',
    parentNodeType: 'FALSY',
    childNodeId: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
    parentNode: {
      id: '5cbf1a25-495b-455d-8a27-353cf776d00c',
      createdAt: '2023-03-21T17:57:58.150Z',
      createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
      deletedAt: null,
      nodeType: 'DECISION',
      nodeName: 'Download Asset',
      nodeNameType: 'downloadAsset',
    },
    childNodes: [
      {
        id: '4795e1e6-1cc6-4df9-8f28-06df07156f29',
        createdAt: '2023-03-21T17:57:58.144Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Inaction Send Email',
        nodeNameType: 'inactionSendEmail',
      },
      {
        id: '7f9c7af3-bfff-467b-90f4-fc721044184e',
        createdAt: '2023-03-21T17:57:58.147Z',
        createdBy: '7d288264-8e0f-4754-9890-ca340c131070',
        deletedAt: null,
        nodeType: 'ACTION',
        nodeName: 'Inaction Update Lead',
        nodeNameType: 'inactionUpdateLead',
      },
    ],
  },
];

export const OLD_NODE_RULES = [
  {
    parentNodeId: 'null',
    parentNodeName: 'null',
    parentNodeType: null,
    parentNodeCategory: 'null',
    // childNodeIds: ['Segment'],
    childNodeIds: [
      {
        id: 'UUID-segment',
        childNodeName: 'Segment',
        parentNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-segment',
    parentNodeName: 'Segment',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-sendEmail',
    parentNodeName: 'Send Email',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: [
    //   'Send Email',
    //   'Update Lead',
    //   'Open Email',
    //   'Download Asset',
    //   'Visit Landing Page',
    //   'Submit Form',
    // ],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-openEmail',
        childNodeName: 'Open Email',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-downloadAsset',
        childNodeName: 'Download Asset',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-visitLandingPage',
        childNodeName: 'Visit Landing Page',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-submitForm',
        childNodeName: 'Submit Form',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-inactionSendEmail',
    parentNodeName: 'Inaction Send Email',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: [
    //   'Send Email',
    //   'Update Lead',
    //   'Open Email',
    //   'Download Asset',
    //   'Visit Landing Page',
    //   'Submit Form',
    // ],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-openEmail',
        childNodeName: 'Open Email',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-downloadAsset',
        childNodeName: 'Download Asset',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-visitLandingPage',
        childNodeName: 'Visit Landing Page',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-submitForm',
        childNodeName: 'Submit Form',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-updateLead',
    parentNodeName: 'Update Lead',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-inactionUpdateLead',
    parentNodeName: 'Inaction Update Lead',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // ===== DECISION BLOCKS ================
  {
    parentNodeId: 'UUID-openEmail', // id of 'Open Email'
    parentNodeName: 'Open Email',
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    parentNodeCategory: 'DECISION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-inactionSendEmail',
        childNodeName: 'Inaction Send Email',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-inactionUpdateLead',
        childNodeName: 'Inaction Update Lead',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-downloadAsset',
    parentNodeName: 'Download Asset',
    parentNodeCategory: 'DECISION',
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-inactionSendEmail',
        childNodeName: 'Inaction Send Email',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-inactionUpdateLead',
        childNodeName: 'Inaction Update Lead',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Download Asset',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
  {
    parentNodeId: 'UUID-visitLandingPage',
    parentNodeName: 'Visit Landing Page',
    parentNodeCategory: 'DECISION',
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-inactionSendEmail',
        childNodeName: 'Inaction Send Email',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-inactionUpdateLead',
        childNodeName: 'Inaction Update Lead',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Visit Landing Page',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
  {
    parentNodeId: 'UUID-submitForm',
    parentNodeName: 'Submit Form',
    parentNodeCategory: 'DECISION',
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-inactionSendEmail',
        childNodeName: 'Inaction Send Email',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-inactionUpdateLead',
        childNodeName: 'Inaction Update Lead',
        nodeType: 'Falsy',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Submit Form',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
];

export const MULTITOUCH_NODE_RULES = [
  {
    parentNodeId: 'null',
    parentNodeName: 'null',
    parentNodeNameType: 'null',
    parentNodeType: null,
    parentNodeCategory: 'null',
    // childNodeIds: ['Segment'],
    childNodeIds: [
      {
        id: 'UUID-segment',
        childNodeName: 'Segment',
        childNodeNameType: 'segment',
        parentNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-contactForm',
        childNodeName: 'Contact Form',
        childNodeNameType: 'contactForm',
        parentNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-segment',
    parentNodeName: 'Segment',
    parentNodeNameType: 'segment',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        childNodeCategory: 'ACTION',
      },
      // {
      //   id: 'UUID-updateLead',
      //   childNodeName: 'Update Lead',
      //   childNodeCategory: 'ACTION',
      // },
    ],
  },
  {
    parentNodeId: 'UUID-contactForm',
    parentNodeName: 'Contact Form',
    parentNodeNameType: 'contactForm',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        childNodeCategory: 'ACTION',
      },
      // {
      //   id: 'UUID-updateLead',
      //   childNodeName: 'Update Lead',
      //   childNodeCategory: 'ACTION',
      // },
    ],
  },
  {
    parentNodeId: 'UUID-sendEmail',
    parentNodeName: 'Send Email',
    parentNodeNameType: 'sendEmail',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: [
    //   'Send Email',
    //   'Update Lead',
    //   'Open Email',
    //   'Download Asset',
    //   'Visit Landing Page',
    //   'Submit Form',
    // ],
    childNodeIds: [
      // {
      //   id: 'UUID-sendEmail',
      //   childNodeName: 'Send Email',
      //   childNodeCategory: 'ACTION',
      // },
      // {
      //   id: 'UUID-updateLead',
      //   childNodeName: 'Update Lead',
      //   childNodeCategory: 'ACTION',
      // },
      {
        id: 'UUID-openEmail',
        childNodeName: 'Open Email',
        childNodeNameType: 'openEmail',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-downloadAsset',
        childNodeName: 'Download Asset',
        childNodeNameType: 'downloadAsset',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-visitLandingPage',
        childNodeName: 'Visit Landing Page',
        childNodeNameType: 'visitLandingPage',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-submitForm',
        childNodeName: 'Submit Form',
        childNodeNameType: 'submitForm',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-notOpenedEmail',
        childNodeName: 'Not Opened Email',
        childNodeNameType: 'notOpenedEmail',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-clickThrough',
        childNodeName: 'Click Through',
        childNodeNameType: 'clickThrough',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-registerForEventOrWebinar',
        childNodeName: 'Register For Event Or Webinar',
        childNodeNameType: 'registerForEventOrWebinar',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  // NEW ACTIONS
  {
    parentNodeId: 'UUID-updateLeadStatus',
    parentNodeName: 'Update Lead Status',
    parentNodeNameType: 'updateLeadStatus',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-changeLeadScore',
    parentNodeName: 'Change Lead Score',
    parentNodeNameType: 'changeLeadScore',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-changeLeadRating',
    parentNodeName: 'Change Lead Rating',
    parentNodeNameType: 'changeLeadRating',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-changeLeadOwner',
    parentNodeName: 'Change Lead Owner',
    parentNodeNameType: 'changeLeadOwner',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-changeAssignLeadTo',
    parentNodeName: 'Change Assign Lead To',
    parentNodeNameType: 'changeAssignLeadTo',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // End of new actions
  {
    parentNodeId: 'UUID-inactionSendEmail',
    parentNodeName: 'Inaction Send Email',
    parentNodeNameType: 'inactionSendEmail',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: [
    //   'Send Email',
    //   'Update Lead',
    //   'Open Email',
    //   'Download Asset',
    //   'Visit Landing Page',
    //   'Submit Form',
    // ],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLead',
        childNodeName: 'Update Lead',
        childNodeNameType: 'updateLead',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-openEmail',
        childNodeName: 'Open Email',
        childNodeNameType: 'openEmail',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-downloadAsset',
        childNodeName: 'Download Asset',
        childNodeNameType: 'downloadAsset',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-visitLandingPage',
        childNodeName: 'Visit Landing Page',
        childNodeNameType: 'visitLandingPage',
        childNodeCategory: 'DECISION',
      },
      {
        id: 'UUID-submitForm',
        childNodeName: 'Submit Form',
        childNodeNameType: 'submitForm',
        childNodeCategory: 'DECISION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-updateLead',
    parentNodeName: 'Update Lead',
    parentNodeNameType: 'updateLead',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-inactionUpdateLead',
    parentNodeName: 'Inaction Update Lead',
    parentNodeNameType: 'inactionUpdateLead',
    parentNodeType: null,
    parentNodeCategory: 'ACTION',
    // childNodeIds: ['Send Email'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // ========== END OF ACTION BLOCK =================================
  // ===== DECISION BLOCKS ===========================
  {
    parentNodeId: 'UUID-openEmail', // id of 'Open Email'
    parentNodeName: 'Open Email',
    parentNodeNameType: 'openEmail',
    parentNodeType: null,
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    parentNodeCategory: 'DECISION',
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLeadStatus',
        childNodeName: 'Update Lead Status',
        childNodeNameType: 'updateLeadStatus',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },

      {
        id: 'UUID-changeLeadScore',
        childNodeName: 'Change Lead Score',
        childNodeNameType: 'changeLeadScore',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadRating',
        childNodeName: 'Change Lead Rating',
        childNodeNameType: 'changeLeadRating',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadOwner',
        childNodeName: 'Change Lead Owner',
        childNodeNameType: 'changeLeadOwner',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeAssignLeadTo',
        childNodeName: 'Change Assign Lead To',
        childNodeNameType: 'changeAssignLeadTo',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  {
    parentNodeId: 'UUID-downloadAsset',
    parentNodeName: 'Download Asset',
    parentNodeNameType: 'downloadAsset',
    parentNodeCategory: 'DECISION',
    parentNodeType: null,
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLeadStatus',
        childNodeName: 'Update Lead Status',
        childNodeNameType: 'updateLeadStatus',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },

      {
        id: 'UUID-changeLeadScore',
        childNodeName: 'Change Lead Score',
        childNodeNameType: 'changeLeadScore',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadRating',
        childNodeName: 'Change Lead Rating',
        childNodeNameType: 'changeLeadRating',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadOwner',
        childNodeName: 'Change Lead Owner',
        childNodeNameType: 'changeLeadOwner',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeAssignLeadTo',
        childNodeName: 'Change Assign Lead To',
        childNodeNameType: 'changeAssignLeadTo',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Download Asset',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
  {
    parentNodeId: 'UUID-visitLandingPage',
    parentNodeName: 'Visit Landing Page',
    parentNodeNameType: 'visitLandingPage',
    parentNodeCategory: 'DECISION',
    parentNodeType: null,
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLeadStatus',
        childNodeName: 'Update Lead Status',
        childNodeNameType: 'updateLeadStatus',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },

      {
        id: 'UUID-changeLeadScore',
        childNodeName: 'Change Lead Score',
        childNodeNameType: 'changeLeadScore',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadRating',
        childNodeName: 'Change Lead Rating',
        childNodeNameType: 'changeLeadRating',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadOwner',
        childNodeName: 'Change Lead Owner',
        childNodeNameType: 'changeLeadOwner',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeAssignLeadTo',
        childNodeName: 'Change Assign Lead To',
        childNodeNameType: 'changeAssignLeadTo',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Visit Landing Page',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
  {
    parentNodeId: 'UUID-submitForm',
    parentNodeName: 'Submit Form',
    parentNodeNameType: 'submitForm',
    parentNodeCategory: 'DECISION',
    parentNodeType: null,
    // parentNodeType: ParentNodeType.TRUTHY,
    // childNodeIds: ['Send Email', 'Update Lead'],
    childNodeIds: [
      {
        id: 'UUID-sendEmail',
        childNodeName: 'Send Email',
        childNodeNameType: 'sendEmail',
        nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-updateLeadStatus',
        childNodeName: 'Update Lead Status',
        childNodeNameType: 'updateLeadStatus',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },

      {
        id: 'UUID-changeLeadScore',
        childNodeName: 'Change Lead Score',
        childNodeNameType: 'changeLeadScore',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadRating',
        childNodeName: 'Change Lead Rating',
        childNodeNameType: 'changeLeadRating',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeLeadOwner',
        childNodeName: 'Change Lead Owner',
        childNodeNameType: 'changeLeadOwner',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
      {
        id: 'UUID-changeAssignLeadTo',
        childNodeName: 'Change Assign Lead To',
        childNodeNameType: 'changeAssignLeadTo',
        // nodeType: 'Truthy',
        childNodeCategory: 'ACTION',
      },
    ],
  },
  // {
  //   parentNodeId: 'Submit Form',
  //   parentNodeType: ParentNodeType.FALSY,
  //   childNodeIds: ['Inaction Send Email', 'Inaction Update Lead'],
  // },
];
